### ISSUE TITLE
Dozentinnenseite zeigt Modulverantwortliche ;)

### ISSUE THREAD

**Issue by cnoss** [th-koeln/medieninformatik-5.0#13]

**Comment by matboehmer** [comment]
Wäre gut alle Leute zu zeigen, also Modulverantwortliche als auch Dozent:innen

**Comment by cnoss** [comment]
Fixed with https://github.com/th-koeln/medieninformatik-5.0/commit/48cd9b279ffee383cd54dbd911c985713a5b0c7a
