### ISSUE TITLE
Immer alle 5 Dimensionen in Kompetenzblume aka Polardiagramm

### ISSUE THREAD

**Issue by matboehmer** [th-koeln/medieninformatik-5.0#49]
ist sonst nicht vergleichbar

![Bildschirmfoto 2023-11-29 um 18 37 14](https://github.com/th-koeln/medieninformatik-5.0/assets/2720107/59ac9470-4d03-4baf-9e05-cd693ef065f7)

**Comment by cnoss** [comment]
fixed with https://github.com/th-koeln/medieninformatik-5.0/commit/e77b23712008397a263c5cfd804e97e794d84643
