### ISSUE TITLE
Spaltensummen in getCurriculumTable

### ISSUE THREAD

**Issue by matboehmer** [th-koeln/medieninformatik-5.0#7]
Wäre cool, wenn in `getCurriculumTable`  in `curriculumTools.11ty.js` unten bei `'Summe Leistungspunkte'` die CP in den Spaltensummen dynamisch addiert werden. Dann stimmt das in den alternativen Studienverlaufplänen auch; dort sind das nicht immer 30 CP.

**Comment by cnoss** [comment]
[Fixed](https://github.com/th-koeln/medieninformatik-5.0/commit/5ef86792712e9fbee072d282237e35f19c4d7209)
